apiVersion: v2
name: hpc-pipeline
description: HPC Deep Learning Pipeline (Distributed Training + Observability)
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: prometheus
    version: 14.0.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: alertmanager
    version: 0.22.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: 6.0.0
    repository: https://grafana.github.io/helm-charts
maintainers:
  - name: HPC Team
    email: hpc-team@example.com