{{- if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hpc-pipeline.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hpc-pipeline.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.servicemonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hpc-pipeline.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.servicemonitor.interval }}
      scrapeTimeout: {{ .Values.servicemonitor.scrapeTimeout }}
{{- end }}
